version: '3.9'

services:
  api:
    build:
      context: ./back
      dockerfile_inline: |
        FROM python:3.11-slim

        ENV PYTHONDONTWRITEBYTECODE=1
        ENV PYTHONUNBUFFERED=1

        WORKDIR /app

        RUN apt-get update \
            && apt-get install -y --no-install-recommends build-essential \
            && rm -rf /var/lib/apt/lists/*

        COPY requirements.txt .
        RUN pip install --no-cache-dir -r requirements.txt

        COPY . .

        EXPOSE 8001

        CMD ["python", "-m", "uvicorn", "api:app", "--host", "0.0.0.0", "--port", "8001"]
    container_name: bacha_api
    restart: unless-stopped
    ports:
      - "8001:8001"
    environment:
      MODEL_CHAT: ${MODEL_CHAT:-qwen2.5:14b}
      MODEL_EMB: ${MODEL_EMB:-bge-m3}
      CHAT_API_SERVER: ${CHAT_API_SERVER:-http://10.10.61.29:11434/api/generate}
      EMBED_API_SERVER: ${EMBED_API_SERVER:-http://10.10.61.29:11434/api/embed}
      MIN_SCORE_RECHIEVAL: ${MIN_SCORE_RECHIEVAL:-0.55}
      
      HOST_POSTGRE: postgres_wiki_db
      PORT_POSTGRE: 5432
      
      DATABASE_PORTGRE: postgres
      USER_POSTGRE: admin
      PASSWORD_POSTGRE: admin123
      
      PYTHONUNBUFFERED: 1
      TZ: "Asia/Ho_Chi_Minh"
      PGTZ: "Asia/Ho_Chi_Minh"
    volumes:
      - ./back:/app

  front:
    build:
      context: ./front
      dockerfile_inline: |
        FROM node:20-alpine

        WORKDIR /app
        COPY package*.json ./
        RUN npm install
        COPY . .

        EXPOSE 4173

        CMD ["npm", "run", "dev", "--", "--host", "0.0.0.0"]
    container_name: bacha_front
    restart: unless-stopped
    ports:
      - "4173:5173"
    volumes:
      - ./front:/app
      - /app/node_modules
    depends_on:
      - api